/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PalpitesRouteImport } from './routes/palpites'
import { Route as IndexRouteImport } from './routes/index'

const PalpitesRoute = PalpitesRouteImport.update({
  id: '/palpites',
  path: '/palpites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/palpites': typeof PalpitesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/palpites': typeof PalpitesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/palpites': typeof PalpitesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/palpites'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/palpites'
  id: '__root__' | '/' | '/palpites'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PalpitesRoute: typeof PalpitesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/palpites': {
      id: '/palpites'
      path: '/palpites'
      fullPath: '/palpites'
      preLoaderRoute: typeof PalpitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PalpitesRoute: PalpitesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
